# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

# get fibs up to value < 4,000,000
# sum them

def fib(n)
  return 1 if n <= 2
  fib(n - 1) + fib(n - 2)
end

def load_fib(n, top, fibs=[])
  if fib(n) <= top
    fibs << fib(n) if fib(n).even?
    load_fib(n + 1, top, fibs)
  end
  fibs
end

fibs_ary = load_fib(2, 4000000)
puts fibs_ary.inject(0) { |r, e| r + e }
